#!/usr/bin/env bun
/**
 * Walk src/resources/knowledge/<collection>/**\/*.md and emit
 * src/resources/knowledge-bundle.generated.ts containing every file's
 * contents inline. This module is imported by `src/knowledge/seed.ts` so
 * the corpus survives `bun build --compile` (which bundles JS but not
 * arbitrary static dirs).
 *
 * Run via: bun scripts/gen-knowledge-bundle.ts
 * Auto-invoked by scripts/build.ts.
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = join(import.meta.dir, '..', 'src', 'resources', 'knowledge');
const OUT = join(import.meta.dir, '..', 'src', 'resources', 'knowledge-bundle.generated.ts');

function walkMd(dir: string): string[] {
  const out: string[] = [];
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith('.')) continue;
    const p = join(dir, entry);
    const st = statSync(p);
    if (st.isDirectory()) out.push(...walkMd(p));
    else if (entry.endsWith('.md')) out.push(p);
  }
  return out;
}

function escapeForBacktick(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const collections = readdirSync(ROOT).filter((e) => {
  const p = join(ROOT, e);
  return statSync(p).isDirectory();
});

const lines: string[] = [
  '/* AUTO-GENERATED by scripts/gen-knowledge-bundle.ts. Do not edit. */',
  '',
  '/** Map of collection → relative-path → file contents. */',
  'export const KNOWLEDGE_BUNDLE: Record<string, Record<string, string>> = {',
];

let totalFiles = 0;
let totalBytes = 0;

for (const col of collections.sort()) {
  const colDir = join(ROOT, col);
  const files = walkMd(colDir);
  if (files.length === 0) continue;
  lines.push(`  ${JSON.stringify(col)}: {`);
  for (const f of files.sort()) {
    const rel = relative(colDir, f);
    const content = readFileSync(f, 'utf8');
    totalFiles++;
    totalBytes += content.length;
    lines.push(`    ${JSON.stringify(rel)}: \`${escapeForBacktick(content)}\`,`);
  }
  lines.push('  },');
}

lines.push('};', '');

writeFileSync(OUT, lines.join('\n'), 'utf8');

const mb = (totalBytes / (1024 * 1024)).toFixed(1);
console.log(`Wrote ${OUT}`);
console.log(`  collections: ${collections.length}`);
console.log(`  files:       ${totalFiles}`);
console.log(`  size:        ${mb} MB`);
